USE [Ardiansyah_KL]
GO
/****** Object:  Table [dbo].[tblAnggota]    Script Date: 5/5/2023 4:37:53 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tblAnggota]') AND type in (N'U'))
DROP TABLE [dbo].[tblAnggota]
GO
/****** Object:  Table [dbo].[tblAbsen]    Script Date: 5/5/2023 4:37:53 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[tblAbsen]') AND type in (N'U'))
DROP TABLE [dbo].[tblAbsen]
GO
USE [master]
GO
/****** Object:  Database [Ardiansyah_KL]    Script Date: 5/5/2023 4:37:53 PM ******/
DROP DATABASE [Ardiansyah_KL]
GO
/****** Object:  Database [Ardiansyah_KL]    Script Date: 5/5/2023 4:37:53 PM ******/
CREATE DATABASE [Ardiansyah_KL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ardiansyah_KL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Ardiansyah_KL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ardiansyah_KL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Ardiansyah_KL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Ardiansyah_KL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ardiansyah_KL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ardiansyah_KL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ardiansyah_KL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ardiansyah_KL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ardiansyah_KL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ardiansyah_KL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Ardiansyah_KL] SET  MULTI_USER 
GO
ALTER DATABASE [Ardiansyah_KL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ardiansyah_KL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ardiansyah_KL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ardiansyah_KL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ardiansyah_KL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ardiansyah_KL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Ardiansyah_KL] SET QUERY_STORE = OFF
GO
USE [Ardiansyah_KL]
GO
/****** Object:  Table [dbo].[tblAbsen]    Script Date: 5/5/2023 4:37:53 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblAbsen](
	[Tanggal] [date] NULL,
	[NIM] [nvarchar](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblAnggota]    Script Date: 5/5/2023 4:37:53 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblAnggota](
	[NIM] [nvarchar](10) NULL,
	[Nama] [nvarchar](50) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Ardiansyah_KL] SET  READ_WRITE 
GO
